# Python Interview Practice

SECTION 1: Data Loading and Basic Operations

In [1]:
import pandas as pd

In [2]:
cust_df = pd.read_csv('customer_data.csv')

In [3]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [4]:
cust_df.describe()

             age  total_purchases  customer_lifetime_value
count  15.000000        15.000000                15.000000
mean   33.866667         5.333333              2709.196667
std     6.139645         1.951800               934.629166
min    24.000000         2.000000              1200.300000
25%    29.500000         4.000000              2025.425000
50%    33.000000         5.000000              2650.400000
75%    38.000000         6.500000              3175.575000
max    45.000000         9.000000              4500.250000

In [5]:
cust_df.dtypes

customer_id                 object
customer_name               object
age                          int64
gender                      object
city                        object
state                       object
registration_date           object
last_purchase_date          object
total_purchases              int64
customer_lifetime_value    float64
dtype: object

In [6]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              15 non-null     object
 1   customer_name            15 non-null     object
 2   age                      15 non-null     int64
 3   gender                   15 non-null     object
 4   city                     15 non-null     object
 5   state                    15 non-null     object
 6   registration_date        15 non-null     object
 7   last_purchase_date       15 non-null     object
 8   total_purchases          15 non-null     int64
 9   customer_lifetime_value  15 non-null     float64
dtypes: float64(1), int64(2), object(7)
memory usage: 1.3+ KB

In [7]:
emp_df = pd.read_csv('employee_performance.csv')
prod_df = pd.read_csv('product_inventory.csv')
sale_df = pd.read_csv('sales_data.csv')

In [8]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [10]:
emp_df.describe()

,employee_id,salary,performance_score,training_hours,projects_completed,manager_id
count,11.000000,11.000000,11.000000,11.000000,11.000000,10.000000
mean,140.000000,68363.636364,4.272727,41.818182,13.545455,221.300000
std,66.037868,20289.271684,0.306891,15.071949,5.574292,42.008068
min,101.000000,52000.000000,3.800000,20.000000,7.000000,201.000000
25%,103.500000,56500.000000,4.050000,32.500000,9.500000,201.000000
50%,106.000000,60000.000000,4.300000,40.000000,12.000000,201.500000
75%,154.500000,73500.000000,4.450000,50.000000,16.500000,202.000000
max,301.000000,120000.000000,4.800000,70.000000,25.000000,301.000000

In [11]:
prod_df.describe()

       cost_price  selling_price  stock_quantity  reorder_level
count   10.000000      10.000000       10.000000      10.000000
mean   233.000000     353.990000       32.000000       9.600000
std    246.274463     340.920323       25.429641       5.719363
min     15.000000      29.990000        4.000000       2.000000
25%     47.500000      92.490000       15.750000       5.750000
50%    140.000000     224.990000       25.500000       9.000000
75%    362.500000     549.990000       41.750000      13.750000
max    750.000000     999.990000       85.000000      20.000000

In [12]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05

In [13]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [15]:
sale_df.describe()

       employee_id   quantity  unit_price  total_amount
count     15.00000  15.000000   15.000000     15.000000
mean     103.60000   1.533333  469.323333    633.318000
std        2.22967   0.743223  359.075533    532.830921
min      101.00000   1.000000   29.990000     79.990000
25%      102.00000   1.000000  139.990000    214.985000
50%      103.00000   1.000000  399.990000    599.990000
75%      105.00000   2.000000  699.990000    949.980000
max      108.00000   3.000000  999.990000   1999.980000

In [18]:
cust_df.isna().sum()

customer_id                0
customer_name              0
age                        0
gender                     0
city                       0
state                      0
registration_date          0
last_purchase_date         0
total_purchases            0
customer_lifetime_value    0
dtype: int64

In [19]:
emp_df.isna().sum()

employee_id           0
employee_name         0
department            0
hire_date             0
salary                0
performance_score     0
training_hours        0
projects_completed    0
manager_id            1
dtype: int64

In [21]:
prod_df.isna().sum()

product_id        0
product_name      0
category          0
brand             0
cost_price        0
selling_price     0
stock_quantity    0
reorder_level     0
supplier_id       0
last_restocked    0
dtype: int64

In [22]:
sale_df.isna().sum()

employee_id         0
employee_name       0
department          0
region              0
sale_date           0
product_category    0
product_name        0
quantity            0
unit_price          0
total_amount        0
customer_id         0
dtype: int64

In [26]:
sale_df.head(5)

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005

In [27]:
sale_df.tail(3)

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

SECTION 2: Data Filtering and Selection

In [29]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [31]:
sale_df[(sale_df['product_category'] == 'Electronics') & (sale_df['total_amount'] > 500)]

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [32]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [37]:
emp_df[(emp_df['hire_date'] >= '2023') & (emp_df['performance_score'] >= 4)]

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0

In [38]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [39]:
cust_df[(cust_df['gender'] == 'Female') & (cust_df['age'] >= 25) & (cust_df['age'] <= 35) & (cust_df['state'] == 'TX')]

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85

In [40]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05

In [41]:
prod_df[prod_df['stock_quantity'] < prod_df['reorder_level']]

Empty DataFrame
Columns: [product_id, product_name, category, brand, cost_price, selling_price, stock_quantity, reorder_level, supplier_id, last_restocked]
Index: []

In [42]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [44]:
sale_df[(sale_df['employee_name'] == 'Jonh Smith') | (sale_df['employee_name'] == 'Sarah Johnson') | (sale_df['employee_name'] == 'Mike Brown')]

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013