# Python Interview Practice

SECTION 1: Data Loading and Basic Operations

In [1]:
import pandas as pd

In [2]:
cust_df = pd.read_csv('customer_data.csv')

In [3]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [4]:
cust_df.describe()

             age  total_purchases  customer_lifetime_value
count  15.000000        15.000000                15.000000
mean   33.866667         5.333333              2709.196667
std     6.139645         1.951800               934.629166
min    24.000000         2.000000              1200.300000
25%    29.500000         4.000000              2025.425000
50%    33.000000         5.000000              2650.400000
75%    38.000000         6.500000              3175.575000
max    45.000000         9.000000              4500.250000

In [5]:
cust_df.dtypes

customer_id                 object
customer_name               object
age                          int64
gender                      object
city                        object
state                       object
registration_date           object
last_purchase_date          object
total_purchases              int64
customer_lifetime_value    float64
dtype: object

In [6]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              15 non-null     object
 1   customer_name            15 non-null     object
 2   age                      15 non-null     int64
 3   gender                   15 non-null     object
 4   city                     15 non-null     object
 5   state                    15 non-null     object
 6   registration_date        15 non-null     object
 7   last_purchase_date       15 non-null     object
 8   total_purchases          15 non-null     int64
 9   customer_lifetime_value  15 non-null     float64
dtypes: float64(1), int64(2), object(7)
memory usage: 1.3+ KB

In [7]:
emp_df = pd.read_csv('employee_performance.csv')
prod_df = pd.read_csv('product_inventory.csv')
sale_df = pd.read_csv('sales_data.csv')

In [8]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [9]:
emp_df.describe()

,employee_id,salary,performance_score,training_hours,projects_completed,manager_id
count,11.000000,11.000000,11.000000,11.000000,11.000000,10.000000
mean,140.000000,68363.636364,4.272727,41.818182,13.545455,221.300000
std,66.037868,20289.271684,0.306891,15.071949,5.574292,42.008068
min,101.000000,52000.000000,3.800000,20.000000,7.000000,201.000000
25%,103.500000,56500.000000,4.050000,32.500000,9.500000,201.000000
50%,106.000000,60000.000000,4.300000,40.000000,12.000000,201.500000
75%,154.500000,73500.000000,4.450000,50.000000,16.500000,202.000000
max,301.000000,120000.000000,4.800000,70.000000,25.000000,301.000000

In [10]:
prod_df.describe()

       cost_price  selling_price  stock_quantity  reorder_level
count   10.000000      10.000000       10.000000      10.000000
mean   233.000000     353.990000       32.000000       9.600000
std    246.274463     340.920323       25.429641       5.719363
min     15.000000      29.990000        4.000000       2.000000
25%     47.500000      92.490000       15.750000       5.750000
50%    140.000000     224.990000       25.500000       9.000000
75%    362.500000     549.990000       41.750000      13.750000
max    750.000000     999.990000       85.000000      20.000000

In [11]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05

In [12]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [13]:
sale_df.describe()

       employee_id   quantity  unit_price  total_amount
count     15.00000  15.000000   15.000000     15.000000
mean     103.60000   1.533333  469.323333    633.318000
std        2.22967   0.743223  359.075533    532.830921
min      101.00000   1.000000   29.990000     79.990000
25%      102.00000   1.000000  139.990000    214.985000
50%      103.00000   1.000000  399.990000    599.990000
75%      105.00000   2.000000  699.990000    949.980000
max      108.00000   3.000000  999.990000   1999.980000

In [14]:
cust_df.isna().sum()

customer_id                0
customer_name              0
age                        0
gender                     0
city                       0
state                      0
registration_date          0
last_purchase_date         0
total_purchases            0
customer_lifetime_value    0
dtype: int64

In [15]:
emp_df.isna().sum()

employee_id           0
employee_name         0
department            0
hire_date             0
salary                0
performance_score     0
training_hours        0
projects_completed    0
manager_id            1
dtype: int64

In [16]:
prod_df.isna().sum()

product_id        0
product_name      0
category          0
brand             0
cost_price        0
selling_price     0
stock_quantity    0
reorder_level     0
supplier_id       0
last_restocked    0
dtype: int64

In [17]:
sale_df.isna().sum()

employee_id         0
employee_name       0
department          0
region              0
sale_date           0
product_category    0
product_name        0
quantity            0
unit_price          0
total_amount        0
customer_id         0
dtype: int64

In [18]:
sale_df.head(5)

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005

In [19]:
sale_df.tail(3)

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

SECTION 2: Data Filtering and Selection

In [20]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [21]:
sale_df[(sale_df['product_category'] == 'Electronics') & (sale_df['total_amount'] > 500)]

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [22]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [23]:
emp_df[(emp_df['hire_date'] >= '2023') & (emp_df['performance_score'] >= 4)]

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0

In [24]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [25]:
cust_df[(cust_df['gender'] == 'Female') & (cust_df['age'] >= 25) & (cust_df['age'] <= 35) & (cust_df['state'] == 'TX')]

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85

In [26]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05

In [27]:
prod_df[prod_df['stock_quantity'] < prod_df['reorder_level']]

Empty DataFrame
Columns: [product_id, product_name, category, brand, cost_price, selling_price, stock_quantity, reorder_level, supplier_id, last_restocked]
Index: []

In [28]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [29]:
sale_df[(sale_df['employee_name'] == 'Jonh Smith') | (sale_df['employee_name'] == 'Sarah Johnson') | (sale_df['employee_name'] == 'Mike Brown')]

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013

SECTION 3: Data Aggregation and Grouping

In [30]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [31]:
sale_df.groupby(['region', 'product_category'])['total_amount'].sum()

region  product_category
East    Clothing             219.96
        Home                 399.99
North   Clothing              99.98
        Electronics         3899.95
South   Electronics         2499.95
        Home                 799.99
West    Clothing              79.99
        Electronics         1199.98
        Home                 299.98
Name: total_amount, dtype: float64

In [32]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [33]:
emp_df.groupby('department')[['salary', 'performance_score']].mean()

              salary  performance_score
department
Executive   120000.0               4.80
Management   83500.0               4.50
Sales        58125.0               4.15

In [34]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [35]:
cust_df.groupby(['state', 'gender'])['customer_id'].count()

state  gender
AZ     Female    1
CA     Male      3
FL     Male      1
IL     Female    1
NC     Female    1
NY     Female    1
OH     Male      1
PA     Male      1
TX     Female    4
       Male      1
Name: customer_id, dtype: int64

In [36]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015

In [37]:
sale_df['sale_date'] = pd.to_datetime(sale_df['sale_date'])

In [38]:
sale_df['year_month'] = sale_df['sale_date'].dt.strftime('%Y-%m')

In [39]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02

In [40]:
sale_df.groupby('year_month')['total_amount'].sum()

year_month
2024-01    6069.84
2024-02    3429.93
Name: total_amount, dtype: float64

In [41]:
sale_df.groupby('employee_name')['total_amount'].sum().sort_values(ascending=False).head(3)

employee_name
John Smith       3299.96
Sarah Johnson    2499.95
Amy Taylor       1199.98
Name: total_amount, dtype: float64

In [42]:
sale_df.head(5)

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01

In [43]:
emp_df.head(5)

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0

In [44]:
emp_sale_df = sale_df.merge(emp_df, how='inner')

In [45]:
emp_sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01,2023-01-10,52000,3.8,25,8,201.0
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01,2022-03-15,65000,4.2,40,12,201.0
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01,2022-11-05,60000,4.1,30,10,202.0
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01,2021-07-20,58000,4.5,35,15,201.0
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01,2021-12-12,63000,4.3,45,14,202.0
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01,2023-01-10,52000,3.8,25,8,201.0
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01,2023-05-18,55000,3.9,20,7,201.0
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01,2022-11-05,60000,4.1,30,10,202.0
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02,2022-03-15,65000,4.2,40,12,201.0
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02,2022-09-30,59000,4.0,38,11,202.0
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02,2021-07-20,58000,4.5,35,15,201.0
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02,2023-02-14,53000,4.4,42,9,201.0
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02,2021-12-12,63000,4.3,45,14,202.0

In [46]:
cus_sale_df = cust_df.merge(sale_df, how='inner')

In [47]:
cus_sale_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value,...,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,year_month
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50,...,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,2024-01
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75,...,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,2024-01
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25,...,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,2024-01
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00,...,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,2024-01
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80,...,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,2024-01
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60,...,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,2024-01
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40,...,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,2024-01
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25,...,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,2024-01
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75,...,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,2024-01
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90,...,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,2024-01
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30,...,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,2024-02
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50,...,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,2024-02
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85,...,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,2024-02
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40,...,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,2024-02
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70,...,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,2024-02

In [48]:
emp_df.merge(sale_df, how='left')

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,North,2024-01-15,Electronics,Laptop,2.0,999.99,1999.98,C001,2024-01
1,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,North,2024-01-18,Electronics,Tablet,1.0,299.99,299.99,C004,2024-01
2,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,North,2024-02-01,Electronics,Laptop,1.0,999.99,999.99,C011,2024-02
3,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,South,2024-01-16,Electronics,Phone,1.0,599.99,599.99,C002,2024-01
4,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,South,2024-01-20,Electronics,Laptop,1.0,999.99,999.99,C006,2024-01
5,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,South,2024-02-03,Electronics,Tablet,3.0,299.99,899.97,C013,2024-02
6,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0,East,2024-01-17,Clothing,Shirt,3.0,29.99,89.97,C003,2024-01
7,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0,East,2024-01-22,Home,Table,1.0,399.99,399.99,C008,2024-01
8,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0,West,2024-01-19,Home,Chair,2.0,149.99,299.98,C005,2024-01
9,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0,West,2024-01-24,Clothing,Dress,1.0,79.99,79.99,C010,2024-01
10,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,North,2024-01-21,Clothing,Pants,2.0,49.99,99.98,C007,2024-01
11,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,North,2024-02-05,Electronics,Phone,1.0,599.99,599.99,C015,2024-02
12,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0,West,2024-01-23,Electronics,Phone,2.0,599.99,1199.98,C009,2024-01
13,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0,South,2024-02-02,Home,Sofa,1.0,799.99,799.99,C012,2024-02
14,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0,East,2024-02-04,Clothing,Jacket,1.0,129.99,129.99,C014,2024-02
15,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
prod_df.merge(sale_df, how='inner')

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked,...,employee_name,department,region,sale_date,product_category,quantity,unit_price,total_amount,customer_id,year_month
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10,...,John Smith,Sales,North,2024-01-15,Electronics,2,999.99,1999.98,C001,2024-01
1,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10,...,Sarah Johnson,Sales,South,2024-01-20,Electronics,1,999.99,999.99,C006,2024-01
2,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10,...,John Smith,Sales,North,2024-02-01,Electronics,1,999.99,999.99,C011,2024-02
3,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12,...,Sarah Johnson,Sales,South,2024-01-16,Electronics,1,599.99,599.99,C002,2024-01
4,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12,...,Amy Taylor,Sales,West,2024-01-23,Electronics,2,599.99,1199.98,C009,2024-01
5,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12,...,Tom Wilson,Sales,North,2024-02-05,Electronics,1,599.99,599.99,C015,2024-02
6,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14,...,John Smith,Sales,North,2024-01-18,Electronics,1,299.99,299.99,C004,2024-01
7,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14,...,Sarah Johnson,Sales,South,2024-02-03,Electronics,3,299.99,899.97,C013,2024-02
8,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08,...,Mike Brown,Sales,East,2024-01-17,Clothing,3,29.99,89.97,C003,2024-01
9,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09,...,Tom Wilson,Sales,North,2024-01-21,Clothing,2,49.99,99.98,C007,2024-01
10,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11,...,Lisa Davis,Sales,West,2024-01-24,Clothing,1,79.99,79.99,C010,2024-01
11,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13,...,Emma White,Sales,East,2024-02-04,Clothing,1,129.99,129.99,C014,2024-02
12,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07,...,Lisa Davis,Sales,West,2024-01-19,Home,2,149.99,299.98,C005,2024-01
13,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06,...,Mike Brown,Sales,East,2024-01-22,Home,1,399.99,399.99,C008,2024-01
14,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05,...,David Lee,Sales,South,2024-02-02,Home,1,799.99,799.99,C012,2024-02

In [50]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [51]:
cust_df['registration_date'] = pd.to_datetime(cust_df['registration_date'])

In [52]:
cust_df['last_purchase_date'] = pd.to_datetime(cust_df['last_purchase_date'])

In [53]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [54]:
emp_df['hire_date'] = pd.to_datetime(emp_df['hire_date'])

In [55]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05

In [56]:
prod_df['last_restocked'] = pd.to_datetime(prod_df['last_restocked'])

In [57]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02

In [58]:
sale_df['sale_date'] = pd.to_datetime(sale_df['sale_date'])

In [59]:
sale_df['sale_date'].dt.year

0     2024
1     2024
2     2024
3     2024
4     2024
5     2024
6     2024
7     2024
8     2024
9     2024
10    2024
11    2024
12    2024
13    2024
14    2024
Name: sale_date, dtype: int32

In [60]:
sale_df['sale_date'].dt.day

0     15
1     16
2     17
3     18
4     19
5     20
6     21
7     22
8     23
9     24
10     1
11     2
12     3
13     4
14     5
Name: sale_date, dtype: int32

In [61]:
sale_df['sale_date'].dt.month

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    2
11    2
12    2
13    2
14    2
Name: sale_date, dtype: int32

In [62]:
sale_df['sale_date'].dt.month_name()

0      January
1      January
2      January
3      January
4      January
5      January
6      January
7      January
8      January
9      January
10    February
11    February
12    February
13    February
14    February
Name: sale_date, dtype: object

In [63]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN

In [64]:
emp_df['experience'] = (pd.Timestamp.now() - emp_df['hire_date']).dt.days

In [65]:
emp_df.head()

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id,experience
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,1184
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,1422
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0,883
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0,949
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,1277

In [66]:
cust_df.head()

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80

In [67]:
cust_df[cust_df['last_purchase_date'] < (pd.Timestamp.now() - pd.Timedelta(days=30))]

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [68]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02

In [69]:
sale_df['week'] = sale_df['sale_date'].dt.dayofyear

In [70]:
sale_df.groupby('week')['total_amount'].sum()

week
15    1999.98
16     599.99
17      89.97
18     299.99
19     299.98
20     999.99
21      99.98
22     399.99
23    1199.98
24      79.99
32     999.99
33     799.99
34     899.97
35     129.99
36     599.99
Name: total_amount, dtype: float64

SECTION 6: Advanced Data Manipulation

In [71]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70

In [72]:
def age_category(x):
    if x < 30:
        return "Young"
    elif x < 45:
        return 'Middle'
    else:
        return 'Senior'


cust_df['age_group'] = cust_df['age'].apply(age_category)

In [73]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value,age_group
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50,Young
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75,Middle
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25,Middle
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00,Middle
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80,Young
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60,Middle
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40,Middle
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25,Senior
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75,Young
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90,Middle
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30,Young
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50,Middle
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85,Middle
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40,Middle
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70,Middle

In [74]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month,week
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01,15
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01,16
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01,17
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01,18
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01,19
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01,20
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01,21
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01,22
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01,23
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01,24
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02,32
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02,33
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02,34
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02,35
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02,36

In [75]:
prod_df['profit_margin'] = prod_df['selling_price'] - prod_df['cost_price']

In [76]:
prod_df

,product_id,product_name,category,brand,cost_price,selling_price,stock_quantity,reorder_level,supplier_id,last_restocked,profit_margin
0,P001,Laptop,Electronics,TechBrand,750.0,999.99,45,10,S001,2024-01-10,249.99
1,P002,Phone,Electronics,PhoneCorp,400.0,599.99,32,15,S002,2024-01-12,199.99
2,P003,Tablet,Electronics,TechBrand,200.0,299.99,28,8,S001,2024-01-14,99.99
3,P004,Shirt,Clothing,FashionCo,15.0,29.99,85,20,S003,2024-01-08,14.99
4,P005,Pants,Clothing,StyleBrand,25.0,49.99,62,15,S004,2024-01-09,24.99
5,P006,Dress,Clothing,FashionCo,40.0,79.99,23,10,S003,2024-01-11,39.99
6,P007,Jacket,Clothing,StyleBrand,70.0,129.99,18,8,S004,2024-01-13,59.99
7,P008,Chair,Home,HomePlus,80.0,149.99,15,5,S005,2024-01-07,69.99
8,P009,Table,Home,FurnitureCo,250.0,399.99,8,3,S006,2024-01-06,149.99
9,P010,Sofa,Home,HomePlus,500.0,799.99,4,2,S005,2024-01-05,299.99

In [77]:
sale_df.groupby(['region', 'employee_name'])['total_amount'].sum().groupby('region').rank(ascending=False)

region  employee_name
East    Emma White       2.0
        Mike Brown       1.0
North   John Smith       1.0
        Tom Wilson       2.0
South   David Lee        2.0
        Sarah Johnson    1.0
West    Amy Taylor       1.0
        Lisa Davis       2.0
Name: total_amount, dtype: float64

In [78]:
employee_sales = sale_df.groupby(['region', 'employee_name'])['total_amount'].sum()

In [79]:
employee_sales

region  employee_name
East    Emma White        129.99
        Mike Brown        489.96
North   John Smith       3299.96
        Tom Wilson        699.97
South   David Lee         799.99
        Sarah Johnson    2499.95
West    Amy Taylor       1199.98
        Lisa Davis        379.97
Name: total_amount, dtype: float64

In [80]:
ranked_sales = employee_sales.groupby('region').rank(method='dense', ascending=False)

In [81]:
ranked_sales.sort_values()

region  employee_name
East    Mike Brown       1.0
North   John Smith       1.0
West    Amy Taylor       1.0
South   Sarah Johnson    1.0
North   Tom Wilson       2.0
East    Emma White       2.0
South   David Lee        2.0
West    Lisa Davis       2.0
Name: total_amount, dtype: float64

In [82]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month,week
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01,15
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01,16
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01,17
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01,18
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01,19
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01,20
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01,21
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01,22
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01,23
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01,24
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02,32
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02,33
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02,34
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02,35
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02,36

In [83]:
sale_df['Percentage_of_Sales'] = round((sale_df['total_amount']/sale_df['total_amount'].sum())*100, 2)

In [84]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month,week,Percentage_of_Sales
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01,15,21.05
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01,16,6.32
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01,17,0.95
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01,18,3.16
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01,19,3.16
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01,20,10.53
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01,21,1.05
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01,22,4.21
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01,23,12.63
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01,24,0.84
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02,32,10.53
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02,33,8.42
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02,34,9.47
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02,35,1.37
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02,36,6.32

In [85]:
sale_df['rolling_sale'] = sale_df.groupby('employee_name')['total_amount'].expanding().sum().reset_index(0, drop=True)

In [86]:
sale_df

,employee_id,employee_name,department,region,sale_date,product_category,product_name,quantity,unit_price,total_amount,customer_id,year_month,week,Percentage_of_Sales,rolling_sale
0,101,John Smith,Sales,North,2024-01-15,Electronics,Laptop,2,999.99,1999.98,C001,2024-01,15,21.05,1999.98
1,102,Sarah Johnson,Sales,South,2024-01-16,Electronics,Phone,1,599.99,599.99,C002,2024-01,16,6.32,599.99
2,103,Mike Brown,Sales,East,2024-01-17,Clothing,Shirt,3,29.99,89.97,C003,2024-01,17,0.95,89.97
3,101,John Smith,Sales,North,2024-01-18,Electronics,Tablet,1,299.99,299.99,C004,2024-01,18,3.16,2299.97
4,104,Lisa Davis,Sales,West,2024-01-19,Home,Chair,2,149.99,299.98,C005,2024-01,19,3.16,299.98
5,102,Sarah Johnson,Sales,South,2024-01-20,Electronics,Laptop,1,999.99,999.99,C006,2024-01,20,10.53,1599.98
6,105,Tom Wilson,Sales,North,2024-01-21,Clothing,Pants,2,49.99,99.98,C007,2024-01,21,1.05,99.98
7,103,Mike Brown,Sales,East,2024-01-22,Home,Table,1,399.99,399.99,C008,2024-01,22,4.21,489.96
8,106,Amy Taylor,Sales,West,2024-01-23,Electronics,Phone,2,599.99,1199.98,C009,2024-01,23,12.63,1199.98
9,104,Lisa Davis,Sales,West,2024-01-24,Clothing,Dress,1,79.99,79.99,C010,2024-01,24,0.84,379.97
10,101,John Smith,Sales,North,2024-02-01,Electronics,Laptop,1,999.99,999.99,C011,2024-02,32,10.53,3299.96
11,107,David Lee,Sales,South,2024-02-02,Home,Sofa,1,799.99,799.99,C012,2024-02,33,8.42,799.99
12,102,Sarah Johnson,Sales,South,2024-02-03,Electronics,Tablet,3,299.99,899.97,C013,2024-02,34,9.47,2499.95
13,108,Emma White,Sales,East,2024-02-04,Clothing,Jacket,1,129.99,129.99,C014,2024-02,35,1.37,129.99
14,105,Tom Wilson,Sales,North,2024-02-05,Electronics,Phone,1,599.99,599.99,C015,2024-02,36,6.32,699.97

SECTION 7: Statistical Analysis

In [87]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id,experience
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,1184
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,1422
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0,883
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0,949
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,1277
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0,755
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0,985
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0,848
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0,2339
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0,1909
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN,2558

In [88]:
emp_df.corr(numeric_only=True)

,employee_id,salary,performance_score,training_hours,projects_completed,manager_id,experience
employee_id,1.000000,0.973833,0.726819,0.863241,0.893201,0.998694,0.911293
salary,0.973833,1.000000,0.753368,0.881536,0.927351,0.934665,0.921296
performance_score,0.726819,0.753368,1.000000,0.872251,0.874710,0.554606,0.837799
training_hours,0.863241,0.881536,0.872251,1.000000,0.928509,0.784376,0.912095
projects_completed,0.893201,0.927351,0.874710,0.928509,1.000000,0.810623,0.981166
manager_id,0.998694,0.934665,0.554606,0.784376,0.810623,1.000000,0.895367
experience,0.911293,0.921296,0.837799,0.912095,0.981166,0.895367,1.000000

In [89]:
cust_df['customer_lifetime_value'].quantile()

np.float64(2650.4)

In [90]:
cust_df

,customer_id,customer_name,age,gender,city,state,registration_date,last_purchase_date,total_purchases,customer_lifetime_value,age_group
0,C001,Alice Brown,28,Female,New York,NY,2023-06-15,2024-01-15,5,2500.50,Young
1,C002,Bob Wilson,35,Male,Los Angeles,CA,2023-03-20,2024-01-16,3,1800.75,Middle
2,C003,Carol Davis,42,Female,Chicago,IL,2023-08-10,2024-01-17,7,3200.25,Middle
3,C004,Daniel Lee,31,Male,Houston,TX,2023-05-05,2024-01-18,4,1950.00,Middle
4,C005,Eva Martinez,26,Female,Phoenix,AZ,2023-09-12,2024-01-19,6,2750.80,Young
5,C006,Frank Taylor,39,Male,Philadelphia,PA,2023-04-18,2024-01-20,8,4100.60,Middle
6,C007,Grace Chen,33,Female,San Antonio,TX,2023-07-22,2024-01-21,5,2300.40,Middle
7,C008,Henry Johnson,45,Male,San Diego,CA,2023-02-28,2024-01-22,9,4500.25,Senior
8,C009,Ivy Thompson,29,Female,Dallas,TX,2023-10-15,2024-01-23,3,1650.75,Young
9,C010,Jack Robinson,37,Male,San Jose,CA,2023-01-30,2024-01-24,6,3150.90,Middle
10,C011,Kate Anderson,24,Female,Austin,TX,2023-11-08,2024-02-01,2,1200.30,Young
11,C012,Liam Garcia,41,Male,Jacksonville,FL,2023-06-25,2024-02-02,7,3800.50,Middle
12,C013,Mia Rodriguez,32,Female,Fort Worth,TX,2023-08-14,2024-02-03,4,2100.85,Middle
13,C014,Noah Martinez,36,Male,Columbus,OH,2023-03-07,2024-02-04,5,2650.40,Middle
14,C015,Olivia Wilson,30,Female,Charlotte,NC,2023-09-19,2024-02-05,6,2980.70,Middle

SECTION 9: Complex Business Questions

In [91]:
prod_sales = sale_df.merge(prod_df, how='inner')

In [92]:
prod_sales.groupby(['region', 'category'])['profit_margin'].sum().groupby('region').nlargest(1)

region  region  category
East    East    Home           149.99
North   North   Electronics    799.96
South   South   Electronics    549.97
West    West    Electronics    199.99
Name: profit_margin, dtype: float64

In [93]:
emp_df

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id,experience
0,101,John Smith,Sales,2022-03-15,65000,4.2,40,12,201.0,1184
1,102,Sarah Johnson,Sales,2021-07-20,58000,4.5,35,15,201.0,1422
2,103,Mike Brown,Sales,2023-01-10,52000,3.8,25,8,201.0,883
3,104,Lisa Davis,Sales,2022-11-05,60000,4.1,30,10,202.0,949
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,1277
5,106,Amy Taylor,Sales,2023-05-18,55000,3.9,20,7,201.0,755
6,107,David Lee,Sales,2022-09-30,59000,4.0,38,11,202.0,985
7,108,Emma White,Sales,2023-02-14,53000,4.4,42,9,201.0,848
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0,2339
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0,1909
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN,2558

In [94]:
metrics = ['performance_score', 'training_hours', 'projects_completed']

In [95]:
avg_metrics = emp_df[metrics].mean()

In [96]:
above_avg = emp_df[metrics] > avg_metrics

In [97]:
above_avg

    performance_score  training_hours  projects_completed
0               False           False               False
1                True           False                True
2               False           False               False
3               False           False               False
4                True            True                True
5               False           False               False
6               False           False               False
7                True            True               False
8                True            True                True
9                True            True                True
10               True            True                True

In [98]:
emp_df[above_avg.all(axis=1)]

,employee_id,employee_name,department,hire_date,salary,performance_score,training_hours,projects_completed,manager_id,experience
4,105,Tom Wilson,Sales,2021-12-12,63000,4.3,45,14,202.0,1277
8,201,Robert Garcia,Management,2019-01-15,85000,4.6,60,20,301.0,2339
9,202,Jennifer Kim,Management,2020-03-20,82000,4.4,55,18,301.0,1909
10,301,Michael Johnson,Executive,2018-06-10,120000,4.8,70,25,NaN,2558

In [99]:
df = pd.DataFrame(data={
    'sl_no': [1, 2 , 3],
    'name': ['prasad', 'ramya', 'pramithi']
})

In [100]:
df

   sl_no      name
0      1    prasad
1      2     ramya
2      3  pramithi

In [101]:
ser = pd.Series(data={
    'name': ['prasad', 'spoorthy', 'chimpa', 'chandu']
})

In [102]:
ser

name    [prasad, spoorthy, chimpa, chandu]
dtype: object

In [106]:
df.iloc[1:3][1:]

   sl_no      name
2      3  pramithi

In [108]:
df2 = pd.DataFrame({
    'order': [4,  5],
    'na': ['no', 'new']
})

In [109]:
df2

   order   na
0      4   no
1      5  new

In [111]:
pd.concat(objs=(df, df2), axis=0)

   sl_no      name  order   na
0    1.0    prasad    NaN  NaN
1    2.0     ramya    NaN  NaN
2    3.0  pramithi    NaN  NaN
0    NaN       NaN    4.0   no
1    NaN       NaN    5.0  new

In [112]:
df3 = pd.DataFrame({
    'sl_no': [4,  5],
    'name': ['no', 'new']
})

In [114]:
pd.concat(objs=(df, df3), axis=0).reset_index()

   index  sl_no      name
0      0      1    prasad
1      1      2     ramya
2      2      3  pramithi
3      0      4        no
4      1      5       new

In [117]:
new = pd.concat(objs=(df, df2), axis=1)

In [122]:
new.iloc[0:2, 1:2]

     name
0  prasad
1   ramya