In [1]:
import pandas as pd

In [2]:
df =pd.DataFrame( {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Month': ['Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb'],
    'Quantity_Sold': [100, 120, 95, 110, 130, 100],
    'Revenue': [5000, 6000, 4500, 5500, 7000, 4800]
})

In [3]:
df

  Product Month  Quantity_Sold  Revenue
0       A   Jan            100     5000
1       B   Jan            120     6000
2       C   Jan             95     4500
3       A   Feb            110     5500
4       B   Feb            130     7000
5       C   Feb            100     4800

In [4]:
df.pivot(index='Product', columns='Month')

        Quantity_Sold      Revenue
Month             Feb  Jan     Feb   Jan
Product
A                 110  100    5500  5000
B                 130  120    7000  6000
C                 100   95    4800  4500

In [5]:
df.pivot_table(index='Product', columns='Month')

        Quantity_Sold        Revenue
Month             Feb    Jan     Feb     Jan
Product
A               110.0  100.0  5500.0  5000.0
B               130.0  120.0  7000.0  6000.0
C               100.0   95.0  4800.0  4500.0

In [6]:

data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03'],
    'Region': ['North', 'South', 'East', 'North', 'South', 'East'],
    'Product': ['Apples', 'Apples', 'Bananas', 'Bananas', 'Apples', 'Apples'],
    'Units Sold': [100, 150, 200, 120, 180, 160],
    'Sales Amount': [1000, 1500, 2200, 1300, 1700, 1550]
}

sales_df = pd.DataFrame(data)

In [7]:
sales_df

         Date Region  Product  Units Sold  Sales Amount
0  2024-01-01  North   Apples         100          1000
1  2024-01-01  South   Apples         150          1500
2  2024-01-01   East  Bananas         200          2200
3  2024-01-02  North  Bananas         120          1300
4  2024-01-02  South   Apples         180          1700
5  2024-01-03   East   Apples         160          1550

In [10]:
sales_df.pivot_table(index='Product', aggfunc='sum')

,Date,Region,Sales Amount,Units Sold
Product,,,,
Apples,2024-01-012024-01-012024-01-022024-01-03,NorthSouthSouthEast,5750,590
Bananas,2024-01-012024-01-02,EastNorth,3500,320

In [11]:
sales_df.pivot_table(values='Sales Amount', index='Region', columns='Product', aggfunc='mean')

Product  Apples  Bananas
Region
East     1550.0   2200.0
North    1000.0   1300.0
South    1600.0      NaN

Total sales by date and region

In [15]:
sales_df.pivot_table(index='Region', columns='Date', values='Sales Amount', aggfunc='sum')

Date    2024-01-01  2024-01-02  2024-01-03
Region
East        2200.0         NaN      1550.0
North       1000.0      1300.0         NaN
South       1500.0      1700.0         NaN

In [16]:
sales_df.pivot_table(values='Sales Amount', index='Region', aggfunc='count')

        Sales Amount
Region
East               2
North              2
South              2

In [20]:
df = pd.read_csv('sales.csv')

In [21]:
df

   OrderID        Date Region SalesPerson   Product  Units  UnitCost  Total
0     1001  2024-01-01   East       Alice  Keyboard     10        20    200
1     1002  2024-01-03   West         Bob     Mouse      5        15     75
2     1003  2024-01-04  South     Charlie   Monitor      2       150    300
3     1004  2024-01-05   East       Alice  Keyboard      6        20    120
4     1005  2024-01-06  North       David     Mouse      7        15    105
5     1006  2024-01-07  South     Charlie   Monitor      3       150    450
6     1007  2024-01-08   West         Bob  Keyboard      4        20     80
7     1008  2024-01-09  North       David   Monitor      1       150    150
8     1009  2024-01-10   East       Alice     Mouse      8        15    120

In [22]:
df.head(5)

   OrderID        Date Region SalesPerson   Product  Units  UnitCost  Total
0     1001  2024-01-01   East       Alice  Keyboard     10        20    200
1     1002  2024-01-03   West         Bob     Mouse      5        15     75
2     1003  2024-01-04  South     Charlie   Monitor      2       150    300
3     1004  2024-01-05   East       Alice  Keyboard      6        20    120
4     1005  2024-01-06  North       David     Mouse      7        15    105

In [23]:
df.shape

(9, 8)

In [24]:
df.columns

Index(['OrderID', 'Date', 'Region', 'SalesPerson', 'Product', 'Units',
       'UnitCost', 'Total'],
      dtype='object')

In [25]:
df.dtypes

OrderID         int64
Date           object
Region         object
SalesPerson    object
Product        object
Units           int64
UnitCost        int64
Total           int64
dtype: object

In [26]:
df['Region'].unique()

array(['East', 'West', 'South', 'North'], dtype=object)

In [27]:
df['Date'] = pd.to_datetime(df['Date'])

In [28]:
df.dtypes

OrderID                 int64
Date           datetime64[ns]
Region                 object
SalesPerson            object
Product                object
Units                   int64
UnitCost                int64
Total                   int64
dtype: object

In [29]:
df.nunique()

OrderID        9
Date           9
Region         4
SalesPerson    4
Product        3
Units          9
UnitCost       3
Total          8
dtype: int64

In [30]:
df[df['SalesPerson'] == 'Alice']

   OrderID       Date Region SalesPerson   Product  Units  UnitCost  Total
0     1001 2024-01-01   East       Alice  Keyboard     10        20    200
3     1004 2024-01-05   East       Alice  Keyboard      6        20    120
8     1009 2024-01-10   East       Alice     Mouse      8        15    120

In [33]:
df[(df['Units'] > 5) & (df['Region'] == 'East')]

   OrderID       Date Region SalesPerson   Product  Units  UnitCost  Total
0     1001 2024-01-01   East       Alice  Keyboard     10        20    200
3     1004 2024-01-05   East       Alice  Keyboard      6        20    120
8     1009 2024-01-10   East       Alice     Mouse      8        15    120

In [34]:
df.sort_values(by='Total', ascending=False)

   OrderID       Date Region SalesPerson   Product  Units  UnitCost  Total
5     1006 2024-01-07  South     Charlie   Monitor      3       150    450
2     1003 2024-01-04  South     Charlie   Monitor      2       150    300
0     1001 2024-01-01   East       Alice  Keyboard     10        20    200
7     1008 2024-01-09  North       David   Monitor      1       150    150
3     1004 2024-01-05   East       Alice  Keyboard      6        20    120
8     1009 2024-01-10   East       Alice     Mouse      8        15    120
4     1005 2024-01-06  North       David     Mouse      7        15    105
6     1007 2024-01-08   West         Bob  Keyboard      4        20     80
1     1002 2024-01-03   West         Bob     Mouse      5        15     75

In [36]:
df.groupby('SalesPerson')['Total'].sum().sort_values(ascending=False)

SalesPerson
Charlie    750
Alice      440
David      255
Bob        155
Name: Total, dtype: int64

In [37]:
df.groupby('Product')['UnitCost'].mean()

Product
Keyboard     20.0
Monitor     150.0
Mouse        15.0
Name: UnitCost, dtype: float64

In [38]:
df.groupby(['Region', 'Product'])['Units'].sum()

Region  Product
East    Keyboard    16
        Mouse        8
North   Monitor      1
        Mouse        7
South   Monitor      5
West    Keyboard     4
        Mouse        5
Name: Units, dtype: int64

In [40]:
df.pivot_table(columns='Product', values='Total', aggfunc='sum', index='Region')

Product  Keyboard  Monitor  Mouse
Region
East        320.0      NaN  120.0
North         NaN    150.0  105.0
South         NaN    750.0    NaN
West         80.0      NaN   75.0

In [57]:
df[df['Date'].dt.month == 1]

   OrderID       Date Region SalesPerson   Product  Units  UnitCost  Total
0     1001 2024-01-01   East       Alice  Keyboard     10        20    200
1     1002 2024-01-03   West         Bob     Mouse      5        15     75
2     1003 2024-01-04  South     Charlie   Monitor      2       150    300
3     1004 2024-01-05   East       Alice  Keyboard      6        20    120
4     1005 2024-01-06  North       David     Mouse      7        15    105
5     1006 2024-01-07  South     Charlie   Monitor      3       150    450
6     1007 2024-01-08   West         Bob  Keyboard      4        20     80
7     1008 2024-01-09  North       David   Monitor      1       150    150
8     1009 2024-01-10   East       Alice     Mouse      8        15    120

In [58]:
df['Weekday'] = df['Date'].dt.weekday