In [1]:
import pandas as pd

In [2]:
cardf = pd.read_csv('car_dubplicates.csv')

In [3]:
cardf.head()

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         2       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla

In [4]:
cardf

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         2       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla
5         6       alto  black  maruti
6         7       alto  black  maruti

In [5]:
cardf.drop_duplicates(subset=['model_name', 'color','brand'], inplace=True, ignore_index=True, )

In [6]:
cardf

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         3    model s  black   tesla
2         4    model x  white   tesla
3         5       alto  white   tesla
4         6       alto  black  maruti

In [7]:
disdf = pd.read_csv('distance_travelled.csv')

In [8]:
disdf

   cars  days  cumulative_distance
0  Car1  Day1                   50
1  Car1  Day2                  100
2  Car1  Day3                  200
3  Car2  Day1                    0
4  Car3  Day1                    0
5  Car3  Day2                   50
6  Car3  Day3                   50
7  Car3  Day4                  100

In [9]:
disdf['daily_distance'] = disdf.groupby('cars')['cumulative_distance'].diff().fillna(0)

In [10]:
disdf

   cars  days  cumulative_distance  daily_distance
0  Car1  Day1                   50             0.0
1  Car1  Day2                  100            50.0
2  Car1  Day3                  200           100.0
3  Car2  Day1                    0             0.0
4  Car3  Day1                    0             0.0
5  Car3  Day2                   50            50.0
6  Car3  Day3                   50             0.0
7  Car3  Day4                  100            50.0

In [11]:
df = pd.read_csv('income.csv')

In [12]:
df

   account_id    income
0         3.0  108939.0
1         2.0   12747.0
2         8.0   87709.0
3         6.0   91796.0
4         NaN       NaN

In [13]:
df.dropna(inplace=True)

In [14]:
df

   account_id    income
0         3.0  108939.0
1         2.0   12747.0
2         8.0   87709.0
3         6.0   91796.0

In [15]:
df['category'] = df['income'].apply(lambda x: 'High' if x > 100000 else("Medium" if x > 50000  else "Low"))

In [16]:
df

   account_id    income category
0         3.0  108939.0     High
1         2.0   12747.0      Low
2         8.0   87709.0   Medium
3         6.0   91796.0   Medium

In [17]:
sales_df = pd.read_csv('sales.csv')

In [18]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000

In [19]:
emp_df = pd.read_csv('employees.csv')

In [20]:
emp_df

  EmpID     Name Department  Salary JoiningDate
0  E001    Alice         HR   40000  2019-07-01
1  E002      Bob         IT   90000  2020-08-15
2  E003  Charlie    Finance  120000  2018-03-20
3  E004    Daisy         IT   60000  2021-10-10
4  E005     Evan         HR   45000  2022-01-12

In [21]:
pro_df = pd.read_csv('products.csv')

In [22]:
pro_df

  ProductID   Product     Category  Stock  Price
0      P001     Mouse  Electronics     25    500
1      P002  Keyboard  Electronics     15    800
2      P003    Laptop  Electronics     10  55000
3      P004      Desk    Furniture      5   7000
4      P005     Chair    Furniture     20   3000

In [23]:
saledet_df = pd.read_csv('sales_details.csv')

In [24]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [25]:
saledet_df.merge(pro_df, right_on='ProductID', left_on='ProductID', how='inner')

   OrderID ProductID  Quantity   Product     Category  Stock  Price
0     1001      P001         2     Mouse  Electronics     25    500
1     1002      P003         1    Laptop  Electronics     10  55000
2     1003      P004         1      Desk    Furniture      5   7000
3     1004      P005         2     Chair    Furniture     20   3000
4     1005      P002         1  Keyboard  Electronics     15    800

In [26]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [27]:
sales_df[sales_df['Quantity'] > 1]

   OrderID        Date Customer Product     Category  Quantity  Price
0     1001  2024-01-05    Alice   Mouse  Electronics         2    500
3     1004  2024-01-07    Alice   Chair    Furniture         2   3000

In [28]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000

In [29]:
sales_df[sales_df['Category']== 'Furniture']

   OrderID        Date Customer Product   Category  Quantity  Price
2     1003  2024-01-07  Charlie    Desk  Furniture         1   7000
3     1004  2024-01-07    Alice   Chair  Furniture         2   3000

In [30]:
sales_df['Total'] = sales_df['Quantity'] * sales_df['Price']

In [31]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [32]:
sales_df[(sales_df['Customer'] == "Alice") & (sales_df['Date'] > '2024-01-06')]

   OrderID        Date Customer Product   Category  Quantity  Price  Total
3     1004  2024-01-07    Alice   Chair  Furniture         2   3000   6000

In [33]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [34]:
sales_df.groupby('Customer')['Total'].sum()

Customer
Alice       7000
Bob        67000
Charlie     7000
Name: Total, dtype: int64

In [35]:
sales_df.groupby('Category')['Price'].mean()

Category
Electronics    22500.0
Furniture       5000.0
Name: Price, dtype: float64

In [36]:
sales_df.groupby('Product')['Quantity'].sum()

Product
Chair      2
Desk       1
Laptop     1
Monitor    1
Mouse      2
Name: Quantity, dtype: int64

In [37]:
sales_df.groupby('Date')['Total'].sum()

Date
2024-01-05     1000
2024-01-06    55000
2024-01-07    13000
2024-01-08    12000
Name: Total, dtype: int64

In [38]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [39]:
mer = saledet_df.merge(pro_df)

In [40]:
mer['Total_sales'] = mer['Quantity'] * mer['Price']

In [41]:
mer.groupby('Category')['Total_sales'].sum()

Category
Electronics    56800
Furniture      13000
Name: Total_sales, dtype: int64

In [42]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800

In [43]:
mer.groupby(by=['Category', 'Product'])['Total_sales'].sum()

Category     Product
Electronics  Keyboard      800
             Laptop      55000
             Mouse        1000
Furniture    Chair        6000
             Desk         7000
Name: Total_sales, dtype: int64

In [44]:
mer[mer['Stock'] == 0]

Empty DataFrame
Columns: [OrderID, ProductID, Quantity, Product, Category, Stock, Price, Total_sales]
Index: []

In [45]:
mer.iloc[0][:3]

OrderID      1001
ProductID    P001
Quantity        2
Name: 0, dtype: object

In [46]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800

In [47]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [48]:
emp_df

  EmpID     Name Department  Salary JoiningDate
0  E001    Alice         HR   40000  2019-07-01
1  E002      Bob         IT   90000  2020-08-15
2  E003  Charlie    Finance  120000  2018-03-20
3  E004    Daisy         IT   60000  2021-10-10
4  E005     Evan         HR   45000  2022-01-12

In [49]:
emp_df['Seniority'] = emp_df['Salary'].apply(lambda x: 'Senior' if x > 100000 else('Mid' if x > 50000 else 'Junior'))

In [50]:
emp_df

  EmpID     Name Department  Salary JoiningDate Seniority
0  E001    Alice         HR   40000  2019-07-01    Junior
1  E002      Bob         IT   90000  2020-08-15       Mid
2  E003  Charlie    Finance  120000  2018-03-20    Senior
3  E004    Daisy         IT   60000  2021-10-10       Mid
4  E005     Evan         HR   45000  2022-01-12    Junior

In [53]:
emp_df['Experience'] = pd.Timestamp.today() - pd.to_datetime(emp_df['JoiningDate'])

In [54]:
emp_df

,EmpID,Name,Department,Salary,JoiningDate,Seniority,Experience
0,E001,Alice,HR,40000,2019-07-01,Junior,2170 days 15:49:17.201446
1,E002,Bob,IT,90000,2020-08-15,Mid,1759 days 15:49:17.201446
2,E003,Charlie,Finance,120000,2018-03-20,Senior,2638 days 15:49:17.201446
3,E004,Daisy,IT,60000,2021-10-10,Mid,1338 days 15:49:17.201446
4,E005,Evan,HR,45000,2022-01-12,Junior,1244 days 15:49:17.201446

In [58]:
emp_df['Experience'] = emp_df['Experience']//365

In [56]:
emp_df

  EmpID     Name Department  Salary JoiningDate Seniority  Experience
0  E001    Alice         HR   40000  2019-07-01    Junior        2170
1  E002      Bob         IT   90000  2020-08-15       Mid        1759
2  E003  Charlie    Finance  120000  2018-03-20    Senior        2638
3  E004    Daisy         IT   60000  2021-10-10       Mid        1338
4  E005     Evan         HR   45000  2022-01-12    Junior        1244

In [59]:
emp_df

  EmpID     Name Department  Salary JoiningDate Seniority  Experience
0  E001    Alice         HR   40000  2019-07-01    Junior           5
1  E002      Bob         IT   90000  2020-08-15       Mid           4
2  E003  Charlie    Finance  120000  2018-03-20    Senior           7
3  E004    Daisy         IT   60000  2021-10-10       Mid           3
4  E005     Evan         HR   45000  2022-01-12    Junior           3

In [60]:
emp_df.groupby('Department').count()

            EmpID  Name  Salary  JoiningDate  Seniority  Experience
Department
Finance         1     1       1            1          1           1
HR              2     2       2            2          2           2
IT              2     2       2            2          2           2

In [61]:
emp_df.groupby('Department')['Salary'].mean()

Department
Finance    120000.0
HR          42500.0
IT          75000.0
Name: Salary, dtype: float64

In [62]:
stu_df = pd.read_csv('students.csv')

In [63]:
stu_df

  StudentID     Name  Maths  Science  English
0      S001    Alice   85.0     78.0       92
1      S002      Bob    NaN     88.0       75
2      S003  Charlie   82.0      NaN       79
3      S004    Daisy   91.0     89.0       94

In [64]:
stu_df.isna().sum()

StudentID    0
Name         0
Maths        1
Science      1
English      0
dtype: int64

In [66]:
stu_df['Maths'].fillna(value=stu_df['Maths'].mean())

0    85.0
1    86.0
2    82.0
3    91.0
Name: Maths, dtype: float64

In [67]:
stu_df

  StudentID     Name  Maths  Science  English
0      S001    Alice   85.0     78.0       92
1      S002      Bob    NaN     88.0       75
2      S003  Charlie   82.0      NaN       79
3      S004    Daisy   91.0     89.0       94

In [68]:
stu_df.fillna(stu_df.mean(numeric_only=True), inplace=True)

In [69]:
stu_df

  StudentID     Name  Maths  Science  English
0      S001    Alice   85.0     78.0       92
1      S002      Bob   86.0     88.0       75
2      S003  Charlie   82.0     85.0       79
3      S004    Daisy   91.0     89.0       94

In [70]:
stu_df['Total'] = stu_df['English'] + stu_df['Maths']+ stu_df['Science']

In [71]:
stu_df

  StudentID     Name  Maths  Science  English  Total
0      S001    Alice   85.0     78.0       92  255.0
1      S002      Bob   86.0     88.0       75  249.0
2      S003  Charlie   82.0     85.0       79  246.0
3      S004    Daisy   91.0     89.0       94  274.0

In [72]:
stu_df.sort_values(by='Total', ascending=False).head(3)

  StudentID   Name  Maths  Science  English  Total
3      S004  Daisy   91.0     89.0       94  274.0
0      S001  Alice   85.0     78.0       92  255.0
1      S002    Bob   86.0     88.0       75  249.0

In [73]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [74]:
sales_df.sort_values(by='Total', ascending=False)

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000

In [75]:
emp_df

  EmpID     Name Department  Salary JoiningDate Seniority  Experience
0  E001    Alice         HR   40000  2019-07-01    Junior           5
1  E002      Bob         IT   90000  2020-08-15       Mid           4
2  E003  Charlie    Finance  120000  2018-03-20    Senior           7
3  E004    Daisy         IT   60000  2021-10-10       Mid           3
4  E005     Evan         HR   45000  2022-01-12    Junior           3

In [76]:
emp_df.sort_values(by="Salary", ascending=False)

  EmpID     Name Department  Salary JoiningDate Seniority  Experience
2  E003  Charlie    Finance  120000  2018-03-20    Senior           7
1  E002      Bob         IT   90000  2020-08-15       Mid           4
3  E004    Daisy         IT   60000  2021-10-10       Mid           3
4  E005     Evan         HR   45000  2022-01-12    Junior           3
0  E001    Alice         HR   40000  2019-07-01    Junior           5

In [77]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800

In [78]:
mer.sort_values(by="Quantity")

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
4,1005,P002,1,Keyboard,Electronics,15,800,800
0,1001,P001,2,Mouse,Electronics,25,500,1000
3,1004,P005,2,Chair,Furniture,20,3000,6000

In [79]:
stu_df

  StudentID     Name  Maths  Science  English  Total
0      S001    Alice   85.0     78.0       92  255.0
1      S002      Bob   86.0     88.0       75  249.0
2      S003  Charlie   82.0     85.0       79  246.0
3      S004    Daisy   91.0     89.0       94  274.0

In [83]:
stu_df.pivot(columns=['Maths', 'Science', 'English'], values=['Total'])

         Total
Maths     85.0   86.0   82.0   91.0
Science   78.0   88.0   85.0   89.0
English     92     75     79     94
0        255.0    NaN    NaN    NaN
1          NaN  249.0    NaN    NaN
2          NaN    NaN  246.0    NaN
3          NaN    NaN    NaN  274.0

In [84]:
# Melt to long format
melted = stu_df.melt(id_vars=['StudentID', 'Name'], 
                     value_vars=['Maths', 'Science', 'English'],
                     var_name='Subject',
                     value_name='Marks')

# Create pivot with Subjects as columns
pivot = melted.pivot_table(index=['StudentID', 'Name'], 
                           columns='Subject', 
                           values='Marks')

In [85]:
melted

   StudentID     Name  Subject  Marks
0       S001    Alice    Maths   85.0
1       S002      Bob    Maths   86.0
2       S003  Charlie    Maths   82.0
3       S004    Daisy    Maths   91.0
4       S001    Alice  Science   78.0
5       S002      Bob  Science   88.0
6       S003  Charlie  Science   85.0
7       S004    Daisy  Science   89.0
8       S001    Alice  English   92.0
9       S002      Bob  English   75.0
10      S003  Charlie  English   79.0
11      S004    Daisy  English   94.0

In [86]:
pivot

Subject            English  Maths  Science
StudentID Name
S001      Alice       92.0   85.0     78.0
S002      Bob         75.0   86.0     88.0
S003      Charlie     79.0   82.0     85.0
S004      Daisy       94.0   91.0     89.0

In [89]:
melthed = stu_df.melt(id_vars=['StudentID', "Name"], value_vars=['Maths', 'Science', "English"], var_name='Subject', value_name='Marks')

In [90]:
melted

   StudentID     Name  Subject  Marks
0       S001    Alice    Maths   85.0
1       S002      Bob    Maths   86.0
2       S003  Charlie    Maths   82.0
3       S004    Daisy    Maths   91.0
4       S001    Alice  Science   78.0
5       S002      Bob  Science   88.0
6       S003  Charlie  Science   85.0
7       S004    Daisy  Science   89.0
8       S001    Alice  English   92.0
9       S002      Bob  English   75.0
10      S003  Charlie  English   79.0
11      S004    Daisy  English   94.0

In [92]:
melted.groupby('Subject')['Marks'].mean()

Subject
English    85.0
Maths      86.0
Science    85.0
Name: Marks, dtype: float64

In [93]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [94]:
sales_df.groupby(by=['Category', 'Customer'])['Quantity'].sum()

Category     Customer
Electronics  Alice       2
             Bob         2
Furniture    Alice       2
             Charlie     1
Name: Quantity, dtype: int64

In [95]:
emp_df

  EmpID     Name Department  Salary JoiningDate Seniority  Experience
0  E001    Alice         HR   40000  2019-07-01    Junior           5
1  E002      Bob         IT   90000  2020-08-15       Mid           4
2  E003  Charlie    Finance  120000  2018-03-20    Senior           7
3  E004    Daisy         IT   60000  2021-10-10       Mid           3
4  E005     Evan         HR   45000  2022-01-12    Junior           3

In [96]:
emp_df.groupby('Department')['Salary'].agg(func=['max', 'min'])

               max     min
Department
Finance     120000  120000
HR           45000   40000
IT           90000   60000

In [97]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800

In [98]:
mer['Profit'] = mer['Total_sales'] * 0.20

In [99]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales,Profit
0,1001,P001,2,Mouse,Electronics,25,500,1000,200.0
1,1002,P003,1,Laptop,Electronics,10,55000,55000,11000.0
2,1003,P004,1,Desk,Furniture,5,7000,7000,1400.0
3,1004,P005,2,Chair,Furniture,20,3000,6000,1200.0
4,1005,P002,1,Keyboard,Electronics,15,800,800,160.0

In [100]:
def stoct_cat(x):
    if x > 10:
        return 'OK'
    else: return 'Low Stock'

In [101]:
mer['Stock Alert'] = mer['Stock'].apply(stoct_cat)

In [102]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales,Profit,Stock Alert
0,1001,P001,2,Mouse,Electronics,25,500,1000,200.0,OK
1,1002,P003,1,Laptop,Electronics,10,55000,55000,11000.0,Low Stock
2,1003,P004,1,Desk,Furniture,5,7000,7000,1400.0,Low Stock
3,1004,P005,2,Chair,Furniture,20,3000,6000,1200.0,OK
4,1005,P002,1,Keyboard,Electronics,15,800,800,160.0,OK

In [103]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales,Profit,Stock Alert
0,1001,P001,2,Mouse,Electronics,25,500,1000,200.0,OK
1,1002,P003,1,Laptop,Electronics,10,55000,55000,11000.0,Low Stock
2,1003,P004,1,Desk,Furniture,5,7000,7000,1400.0,Low Stock
3,1004,P005,2,Chair,Furniture,20,3000,6000,1200.0,OK
4,1005,P002,1,Keyboard,Electronics,15,800,800,160.0,OK