In [1]:
import pandas as pd

In [2]:
cardf = pd.read_csv('car_dubplicates.csv')

In [3]:
cardf.head()

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         2       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla

In [4]:
cardf

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         2       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla
5         6       alto  black  maruti
6         7       alto  black  maruti

In [ ]:
cardf.drop_duplicates(subset=['model_name', 'color','brand'], inplace=True, ignore_index=True, )

In [15]:
cardf

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         3    model s  black   tesla
2         4    model x  white   tesla
3         5       alto  white   tesla
4         6       alto  black  maruti

In [16]:
disdf = pd.read_csv('distance_travelled.csv')

In [17]:
disdf

   cars  days  cumulative_distance
0  Car1  Day1                   50
1  Car1  Day2                  100
2  Car1  Day3                  200
3  Car2  Day1                    0
4  Car3  Day1                    0
5  Car3  Day2                   50
6  Car3  Day3                   50
7  Car3  Day4                  100

In [24]:
disdf['daily_distance'] = disdf.groupby('cars')['cumulative_distance'].diff().fillna(0)

In [25]:
disdf

   cars  days  cumulative_distance  daily_distance
0  Car1  Day1                   50             0.0
1  Car1  Day2                  100            50.0
2  Car1  Day3                  200           100.0
3  Car2  Day1                    0             0.0
4  Car3  Day1                    0             0.0
5  Car3  Day2                   50            50.0
6  Car3  Day3                   50             0.0
7  Car3  Day4                  100            50.0

In [26]:
df = pd.read_csv('income.csv')

In [27]:
df

   account_id    income
0         3.0  108939.0
1         2.0   12747.0
2         8.0   87709.0
3         6.0   91796.0
4         NaN       NaN

In [30]:
df.dropna(inplace=True)

In [31]:
df

   account_id    income
0         3.0  108939.0
1         2.0   12747.0
2         8.0   87709.0
3         6.0   91796.0

In [36]:
df['category'] = df['income'].apply(lambda x: 'High' if x > 100000 else("Medium" if x > 50000  else "Low"))

In [37]:
df

   account_id    income category
0         3.0  108939.0     High
1         2.0   12747.0      Low
2         8.0   87709.0   Medium
3         6.0   91796.0   Medium

In [38]:
sales_df = pd.read_csv('sales.csv')

In [39]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000

In [42]:
emp_df = pd.read_csv('employees.csv')

In [43]:
emp_df

  EmpID     Name Department  Salary JoiningDate
0  E001    Alice         HR   40000  2019-07-01
1  E002      Bob         IT   90000  2020-08-15
2  E003  Charlie    Finance  120000  2018-03-20
3  E004    Daisy         IT   60000  2021-10-10
4  E005     Evan         HR   45000  2022-01-12

In [44]:
pro_df = pd.read_csv('products.csv')

In [45]:
pro_df

  ProductID   Product     Category  Stock  Price
0      P001     Mouse  Electronics     25    500
1      P002  Keyboard  Electronics     15    800
2      P003    Laptop  Electronics     10  55000
3      P004      Desk    Furniture      5   7000
4      P005     Chair    Furniture     20   3000

In [46]:
saledet_df = pd.read_csv('sales_details.csv')

In [47]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [52]:
saledet_df.merge(pro_df, right_on='ProductID', left_on='ProductID', how='inner')

   OrderID ProductID  Quantity   Product     Category  Stock  Price
0     1001      P001         2     Mouse  Electronics     25    500
1     1002      P003         1    Laptop  Electronics     10  55000
2     1003      P004         1      Desk    Furniture      5   7000
3     1004      P005         2     Chair    Furniture     20   3000
4     1005      P002         1  Keyboard  Electronics     15    800

In [53]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [54]:
sales_df[sales_df['Quantity'] > 1]

   OrderID        Date Customer Product     Category  Quantity  Price
0     1001  2024-01-05    Alice   Mouse  Electronics         2    500
3     1004  2024-01-07    Alice   Chair    Furniture         2   3000

In [55]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000

In [56]:
sales_df[sales_df['Category']== 'Furniture']

   OrderID        Date Customer Product   Category  Quantity  Price
2     1003  2024-01-07  Charlie    Desk  Furniture         1   7000
3     1004  2024-01-07    Alice   Chair  Furniture         2   3000

In [57]:
sales_df['Total'] = sales_df['Quantity'] * sales_df['Price']

In [58]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [62]:
sales_df[(sales_df['Customer'] == "Alice") & (sales_df['Date'] > '2024-01-06')]

   OrderID        Date Customer Product   Category  Quantity  Price  Total
3     1004  2024-01-07    Alice   Chair  Furniture         2   3000   6000

In [63]:
sales_df

   OrderID        Date Customer  Product     Category  Quantity  Price  Total
0     1001  2024-01-05    Alice    Mouse  Electronics         2    500   1000
1     1002  2024-01-06      Bob   Laptop  Electronics         1  55000  55000
2     1003  2024-01-07  Charlie     Desk    Furniture         1   7000   7000
3     1004  2024-01-07    Alice    Chair    Furniture         2   3000   6000
4     1005  2024-01-08      Bob  Monitor  Electronics         1  12000  12000

In [68]:
sales_df.groupby('Customer')['Total'].sum()

Customer
Alice       7000
Bob        67000
Charlie     7000
Name: Total, dtype: int64

In [69]:
sales_df.groupby('Category')['Price'].mean()

Category
Electronics    22500.0
Furniture       5000.0
Name: Price, dtype: float64

In [70]:
sales_df.groupby('Product')['Quantity'].sum()

Product
Chair      2
Desk       1
Laptop     1
Monitor    1
Mouse      2
Name: Quantity, dtype: int64

In [71]:
sales_df.groupby('Date')['Total'].sum()

Date
2024-01-05     1000
2024-01-06    55000
2024-01-07    13000
2024-01-08    12000
Name: Total, dtype: int64

In [72]:
saledet_df

   OrderID ProductID  Quantity
0     1001      P001         2
1     1002      P003         1
2     1003      P004         1
3     1004      P005         2
4     1005      P002         1

In [74]:
mer = saledet_df.merge(pro_df)

In [76]:
mer['Total_sales'] = mer['Quantity'] * mer['Price']

In [78]:
mer.groupby('Category')['Total_sales'].sum()

Category
Electronics    56800
Furniture      13000
Name: Total_sales, dtype: int64

In [79]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800

In [80]:
mer.groupby(by=['Category', 'Product'])['Total_sales'].sum()

Category     Product
Electronics  Keyboard      800
             Laptop      55000
             Mouse        1000
Furniture    Chair        6000
             Desk         7000
Name: Total_sales, dtype: int64

In [83]:
mer[mer['Stock'] == 0]

Empty DataFrame
Columns: [OrderID, ProductID, Quantity, Product, Category, Stock, Price, Total_sales]
Index: []

In [93]:
mer.iloc[0][:3]

OrderID      1001
ProductID    P001
Quantity        2
Name: 0, dtype: object

In [86]:
mer

,OrderID,ProductID,Quantity,Product,Category,Stock,Price,Total_sales
0,1001,P001,2,Mouse,Electronics,25,500,1000
1,1002,P003,1,Laptop,Electronics,10,55000,55000
2,1003,P004,1,Desk,Furniture,5,7000,7000
3,1004,P005,2,Chair,Furniture,20,3000,6000
4,1005,P002,1,Keyboard,Electronics,15,800,800