In [1]:
def is_adult(age):
    if age > 18:
        print("adult")
    else:
        print("Minor")

In [2]:
is_adult(20)

adult

In [3]:
is_adult(0)

Minor

In [5]:
new_list = [32, 25, 0, 95]
sorted(new_list, reverse=True)

[95, 32, 25, 0]

In [5]:
list=[52,63,45,89, 3, 4, 6, 8, 9, 2, 10]
for x in list:
    if x < 10:
        print(x)

3
4
6
8
9
2

In [11]:
list[1:4]

[63, 45, 89]

In [19]:
name = 'prasad Hp'

In [24]:
name.split()[0]

'prasad'

In [21]:
len(name)

9

In [22]:
len(list)

11

In [26]:
name.lower().islower()

True

In [28]:
name = 'prasad hp'

In [29]:
name.islower()

True

In [30]:
name = '    prasad Hp    '

In [32]:
name.rstrip()

'    prasad Hp'

In [36]:
'Pra' not in name

True

In [40]:
25 ** 0.5

5.0

In [38]:
5 ** 2

25

In [46]:
round(2.054, 2)

2.05

In [47]:
import math;

In [48]:
x = int(input("Enter the age: "))
type(x)

int

In [4]:

def drink_water(temp):
    if temp > 30:
        print("Drink Water \nTemp is High")
    elif temp < 25:
        print("Drink Some Water")
    else:
        print("Dont drink water")

In [5]:
drink_water(65)

Drink Water
Temp is High

In [7]:
drink_water(0)

Drink Some Water

In [8]:
drink_water(27)

Dont drink water

In [22]:
col = []
for x in range(0, 11, 2):
    if x > 7:
        break
    col.append(x)
    print(col)

[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]

In [26]:
for x in range(3):
    print(f'Outer {x}')
    for y in range(3):
        print(f'Inner {y}')

Outer 0
Inner 0
Inner 1
Inner 2
Outer 1
Inner 0
Inner 1
Inner 2
Outer 2
Inner 0
Inner 1
Inner 2

In [38]:
list = [1,2,3,4,5,6,7,8,9,10]

In [28]:
ran = range(11)

In [43]:
for x in range(10):
    if (ran[x] % 2 == 0):
        print(ran[x])

0
2
4
6
8

In [47]:
command = ""
while command != 'quit':
    command = (input("Command ?")).lower()
    print("dad", command)
print("Code ended")

dad quit
Code ended

In [50]:
count = 0
for x in range(1,9):
    if x % 2 == 0:
        print(x)
        count = count + 1
print(f'There are {count} even numbers')

2
4
6
8
There are 4 even numbers

In [1]:
import numpy as np

In [2]:
list = np.array(object=(6,7,7,9))

In [3]:
list

array([6, 7, 7, 9])

In [4]:
a = []
b = []
for x in range(10):
    a.append(x)

for y in range(10, 20):
    b.append(y)

a_arr = np.array(a)
b_arr = np.array(b)

In [5]:
a_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a_arr * b_arr

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [8]:
a_arr + b_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
a_arr.dtype

dtype('int64')

In [10]:
a_arr.shape

(10,)

In [ ]:
a_arr.s

np.int64(9)

In [7]:
import pandas as pd

# Sample time-series data
date_rng = pd.date_range(start='2024-01-01', end='2024-01-10', freq='D')
df = pd.DataFrame({'date': date_rng, 'sales': [100, 200, 150, 120, 130, 160, 180, 175, 190, 210]})

In [8]:
df.set_index('date', inplace=True)

In [12]:
df.resample('3D').mean()

                 sales
date
2024-01-01  150.000000
2024-01-04  136.666667
2024-01-07  181.666667
2024-01-10  210.000000

In [17]:
df.rolling(window='3D').mean()

                 sales
date
2024-01-01  100.000000
2024-01-02  150.000000
2024-01-03  150.000000
2024-01-04  156.666667
2024-01-05  133.333333
2024-01-06  136.666667
2024-01-07  156.666667
2024-01-08  171.666667
2024-01-09  181.666667
2024-01-10  191.666667

In [16]:
df

            sales
date
2024-01-01    100
2024-01-02    200
2024-01-03    150
2024-01-04    120
2024-01-05    130
2024-01-06    160
2024-01-07    180
2024-01-08    175
2024-01-09    190
2024-01-10    210