In [20]:
from sqlalchemy import create_engine, text
import pandas as pd

In [16]:
engine = create_engine("postgresql+psycopg2://postgres:gowda@localhost:5432/Practice")

In [51]:
with engine.connect() as connection:
    result = connection.execute(text('SELECT * FROM employee'))
    df = pd.DataFrame(result)

In [24]:
df.groupby('gender')['salary'].mean()

gender
Female     59000.0
Male       62600.0
male      105000.0
Name: salary, dtype: float64

In [25]:
df

    id    name  salary  gender
0    1  prasad  105000    male
1    3   Alice   55000  Female
2    4     Bob   62000    Male
3    5   Carol   58000  Female
4    6   David   73000    Male
5    7     Eve   50000  Female
6    8   Frank   68000    Male
7    9   Grace   72000  Female
8   10   Henry   46000    Male
9   11     Ivy   60000  Female
10  12    Jack   64000    Male

In [26]:
df['rank_min'] = df['salary'].rank(method='min', ascending=False)

In [27]:
df['rank_avg'] = df['salary'].rank(method='average', ascending=False)

In [28]:
df['rank_dense'] = df['salary'].rank(method='dense', ascending=False)

In [29]:
df['rank_max'] = df['salary'].rank(method='max', ascending=False)

In [30]:
df['rank'] = df['salary'].rank(method='first', ascending=False)

In [32]:
df.sort_values(by='rank_min')

    id    name  salary  gender  rank_min  rank_avg  rank_dense  rank_max  rank
0    1  prasad  105000    male       1.0       1.0         1.0       1.0   1.0
4    6   David   73000    Male       2.0       2.0         2.0       2.0   2.0
7    9   Grace   72000  Female       3.0       3.0         3.0       3.0   3.0
6    8   Frank   68000    Male       4.0       4.0         4.0       4.0   4.0
10  12    Jack   64000    Male       5.0       5.0         5.0       5.0   5.0
2    4     Bob   62000    Male       6.0       6.0         6.0       6.0   6.0
9   11     Ivy   60000  Female       7.0       7.0         7.0       7.0   7.0
3    5   Carol   58000  Female       8.0       8.0         8.0       8.0   8.0
1    3   Alice   55000  Female       9.0       9.0         9.0       9.0   9.0
5    7     Eve   50000  Female      10.0      10.0        10.0      10.0  10.0
8   10   Henry   46000    Male      11.0      11.0        11.0      11.0  11.0

In [33]:
df = pd.read_csv('score.csv')

In [34]:
df

   StudentID     Name Subject  Score
0        101    Alice    Math     90
1        102      Bob    Math     85
2        103  Charlie    Math     90
3        104    David    Math     80
4        105      Eve    Math     85
5        106    Frank    Math     70

In [35]:
df['rank_min'] = df['Score'].rank(method='min', ascending=False)

In [36]:
df['rank_avg'] = df['Score'].rank(method='average', ascending=False)

In [37]:
df['rank_max'] = df['Score'].rank(method='max', ascending=False)

In [38]:
df['rank_dense'] = df['Score'].rank(method='dense', ascending=False)

In [39]:
df['rank'] = df['Score'].rank(method='first', ascending=False)

In [40]:
df

,StudentID,Name,Subject,Score,rank_min,rank_avg,rank_max,rank_dense,rank
0,101,Alice,Math,90,1.0,1.5,2.0,1.0,1.0
1,102,Bob,Math,85,3.0,3.5,4.0,2.0,3.0
2,103,Charlie,Math,90,1.0,1.5,2.0,1.0,2.0
3,104,David,Math,80,5.0,5.0,5.0,3.0,5.0
4,105,Eve,Math,85,3.0,3.5,4.0,2.0,4.0
5,106,Frank,Math,70,6.0,6.0,6.0,4.0,6.0

In [41]:
df.sort_values(by='rank')

,StudentID,Name,Subject,Score,rank_min,rank_avg,rank_max,rank_dense,rank
0,101,Alice,Math,90,1.0,1.5,2.0,1.0,1.0
2,103,Charlie,Math,90,1.0,1.5,2.0,1.0,2.0
1,102,Bob,Math,85,3.0,3.5,4.0,2.0,3.0
4,105,Eve,Math,85,3.0,3.5,4.0,2.0,4.0
3,104,David,Math,80,5.0,5.0,5.0,3.0,5.0
5,106,Frank,Math,70,6.0,6.0,6.0,4.0,6.0

In [42]:
cols = ['Student_Id', 'Student_Name', "Subjects", "Marks_Obtained"]

In [43]:
df = pd.read_csv('score.csv', names=cols)

In [50]:
df

  Student_Id Student_Name Subjects Marks_Obtained
1        101        Alice     Math             90
2        102          Bob     Math             85
3        103      Charlie     Math             90
4        104        David     Math             80
5        105          Eve     Math             85
6        106        Frank     Math             70

In [49]:
df.drop(index=0, axis=0).reset_index(drop=True)

KeyError: '[0] not found in axis'

In [52]:
df.head()

   id    name  salary  gender
0   1  prasad  105000    male
1   3   Alice   55000  Female
2   4     Bob   62000    Male
3   5   Carol   58000  Female
4   6   David   73000    Male

In [ ]:
df.pivot_table(values='salary', columns=)

ValueError: No group keys passed!