In [2]:
import numpy as np

# Sales data: rows = days, columns = products A, B, C
sales_data = np.array([
    [100, 200, 300],  # Day 1
    [150, 180, 250],  # Day 2
    [200, 160, 230],  # Day 3
    [170, 190, 210],  # Day 4
    [160, 220, 310]   # Day 5
])

product_names = ['A', 'B', 'C']

In [4]:
sales_data.shape

(5, 3)

In [5]:
import pandas as pd

data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Department': ['Sales', 'HR', 'Sales', 'IT', 'Sales'],
    'JoinDate': ['2022-01-15', '2021-11-01', '2023-06-20', '2020-02-28', '2022-09-10'],
    'Salary': [60000, 52000, 65000, 70000, 63000],
    'PerformanceScore': [88, 76, 90, 95, 85]
}

df = pd.DataFrame(data)

In [6]:
df

   EmployeeID     Name Department    JoinDate  Salary  PerformanceScore
0         101    Alice      Sales  2022-01-15   60000                88
1         102      Bob         HR  2021-11-01   52000                76
2         103  Charlie      Sales  2023-06-20   65000                90
3         104    Diana         IT  2020-02-28   70000                95
4         105    Ethan      Sales  2022-09-10   63000                85

In [7]:
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [9]:
df[df['Department'] == "Sales"]

   EmployeeID     Name Department   JoinDate  Salary  PerformanceScore
0         101    Alice      Sales 2022-01-15   60000                88
2         103  Charlie      Sales 2023-06-20   65000                90
4         105    Ethan      Sales 2022-09-10   63000                85

In [10]:
df[df['PerformanceScore'] > 85]

   EmployeeID     Name Department   JoinDate  Salary  PerformanceScore
0         101    Alice      Sales 2022-01-15   60000                88
2         103  Charlie      Sales 2023-06-20   65000                90
3         104    Diana         IT 2020-02-28   70000                95

In [11]:
df[['Name', 'Salary']]

      Name  Salary
0    Alice   60000
1      Bob   52000
2  Charlie   65000
3    Diana   70000
4    Ethan   63000

In [14]:
df.groupby("Department").agg({'Salary':'mean'})

                  Salary
Department
HR          52000.000000
IT          70000.000000
Sales       62666.666667

In [18]:
df[df['Department']== 'Sales']['Salary'].sum()

np.int64(188000)

In [20]:
df.sort_values(by='JoinDate')

   EmployeeID     Name Department   JoinDate  Salary  PerformanceScore
3         104    Diana         IT 2020-02-28   70000                95
1         102      Bob         HR 2021-11-01   52000                76
0         101    Alice      Sales 2022-01-15   60000                88
4         105    Ethan      Sales 2022-09-10   63000                85
2         103  Charlie      Sales 2023-06-20   65000                90

In [22]:
df[df['JoinDate'] > '2022-01-01']

   EmployeeID     Name Department   JoinDate  Salary  PerformanceScore
0         101    Alice      Sales 2022-01-15   60000                88
2         103  Charlie      Sales 2023-06-20   65000                90
4         105    Ethan      Sales 2022-09-10   63000                85

In [23]:
df['JoinDate'].dt.year

0    2022
1    2021
2    2023
3    2020
4    2022
Name: JoinDate, dtype: int32

In [25]:
df.isna().sum()

EmployeeID          0
Name                0
Department          0
JoinDate            0
Salary              0
PerformanceScore    0
dtype: int64

In [1]:
import pandas as pd

df_info = pd.DataFrame({
    'EmployeeID': [101, 102, 103, 104],
    'Name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Diana Prince'],
    'Department': ['Sales', 'HR', 'IT', 'Sales']
})

In [2]:
df_salary = pd.DataFrame({
    'EmployeeID': [101, 102, 104, 105],
    'Salary': [60000, 52000, 70000, 48000]
})

In [3]:
df_new = pd.DataFrame({
    'EmployeeID': [106, 107],
    'Name': ['Ethan Ray', 'Fiona Dale'],
    'Department': ['Marketing', 'Finance']
})

In [4]:
df_info

   EmployeeID           Name Department
0         101  Alice Johnson      Sales
1         102      Bob Smith         HR
2         103  Charlie Brown         IT
3         104   Diana Prince      Sales

In [5]:
df_salary

   EmployeeID  Salary
0         101   60000
1         102   52000
2         104   70000
3         105   48000

In [6]:
df_new

   EmployeeID        Name Department
0         106   Ethan Ray  Marketing
1         107  Fiona Dale    Finance

In [16]:
df_info.merge(right=df_salary, left=df_new, left_on='EmployeeID', right_on='EmployeeID', how='outer')

TypeError: DataFrame.merge() got an unexpected keyword argument 'left'

In [22]:
pd.concat([df_info, df_new], axis=1)

   EmployeeID           Name Department  EmployeeID        Name Department
0         101  Alice Johnson      Sales       106.0   Ethan Ray  Marketing
1         102      Bob Smith         HR       107.0  Fiona Dale    Finance
2         103  Charlie Brown         IT         NaN         NaN        NaN
3         104   Diana Prince      Sales         NaN         NaN        NaN

In [20]:
df_info

   EmployeeID           Name Department
0         101  Alice Johnson      Sales
1         102      Bob Smith         HR
2         103  Charlie Brown         IT
3         104   Diana Prince      Sales

In [21]:
df_new

   EmployeeID        Name Department
0         106   Ethan Ray  Marketing
1         107  Fiona Dale    Finance

In [28]:
df_info['Name'].str.split().str[0]

0      Alice
1        Bob
2    Charlie
3      Diana
Name: Name, dtype: object